# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Flash Chat iOS13' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flash Chat iOS13

pod 'Alamofire', '~> 5.0.0-rc.3'

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

pod 'Firebase/Auth'
pod 'Firebase/Firestore'


end
